In [1]:
print("박용현", "30201062")

박용현 30201062


In [2]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import matplotlib.pyplot as plt

Duplicate key in file '/Users/yonghyunpark/.matplotlib/matplotlibrc', line 2 ('backend: TkAgg')


In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [5]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
print(obj2['a'])
obj2['d'] = 6
print(obj2[['c', 'a', 'd']])

-5
c    3
a   -5
d    6
dtype: int64


In [8]:
print(obj2 > 0)
obj2[obj2>0]

d     True
b     True
a    False
c     True
dtype: bool


d    6
b    7
c    3
dtype: int64

In [9]:
print(obj2*2)
print(np.exp(obj2))

d    12
b    14
a   -10
c     6
dtype: int64
d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64


In [10]:
print('b' in obj2.index)
print('e' in obj2.index)

True
False


In [11]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [12]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index= states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [13]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [14]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [15]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year' : [2000,2001,2002,2001,2002,2003],
'pop' : [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [17]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [18]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [19]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [20]:
frame.describe()

year       pop
count     6.000000  6.000000
mean   2001.500000  2.550000
std       1.048809  0.836062
min    2000.000000  1.500000
25%    2001.000000  1.875000
50%    2001.500000  2.650000
75%    2002.000000  3.125000
max    2003.000000  3.600000

In [21]:
frame = frame.astype({'year' : str})
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [22]:
pd.get_dummies(frame)

pop  state_Nevada  state_Ohio  year_2000  year_2001  year_2002  year_2003
0  1.5             0           1          1          0          0          0
1  1.7             0           1          0          1          0          0
2  3.6             0           1          0          0          1          0
3  2.4             1           0          0          1          0          0
4  2.9             1           0          0          0          1          0
5  3.2             1           0          0          0          0          1

In [23]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [24]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])

print(frame2)
print(frame2.columns)
print(frame2.index)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN
Index(['year', 'state', 'pop', 'debt'], dtype='object')
Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')


In [25]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [26]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [27]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [28]:
frame2.loc['three', 'state']

'Ohio'

In [29]:
frame2['debt'] = 16.5
print(frame2)
frame2['debt'] = np.arange(6.)
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5
       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0


In [30]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [31]:
frame2['eastern'] = frame2.state =='Ohio'
frame2 # 

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [32]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [33]:
pop = {'Nevada' : {2001: 2.4, 2002:2.9},
'Ohio' : {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [34]:
frame3 = pd.DataFrame(pop)
print(frame3.index)
frame3

Int64Index([2001, 2002, 2000], dtype='int64')


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [35]:
frame3.T # 데이터프레임 Transpose시키기 --> 인덱스와 컬럼의 위치를 바꿈.

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [36]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [37]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
'Nevada' : frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [38]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [39]:
%time for _ in range(10) : my_arr2 = my_arr*2
# ndarray 연산 시간 측정
%time for _ in range(10) : my_list2 = [x*2 for x in my_list] # list 연산 시간 측정

CPU times: user 12.8 ms, sys: 5.15 ms, total: 17.9 ms
Wall time: 17.2 ms
CPU times: user 550 ms, sys: 158 ms, total: 708 ms
Wall time: 708 ms


## 문제 풀이

In [40]:
# 문제 1. 표준 정규 분포(평균 0, 표준편차 1)에서 난수 ndarray 생성하기
# ndarray 이름: data
# ndarray 크기: (2, 3)

# 정답 1.
import numpy as np
data = np.random.randn(2,3)
data

array([[-0.02392369,  0.12152216,  0.29665341],
       [ 0.80671732, -0.91848145,  1.20816639]])

In [41]:
# 문제 2. 0부터 1사이의 균일 분포에서 난수 ndarray 생성하기
# ndarray 이름: data2
# ndarray 크기: (2, 3)

# 정답 2.
import numpy as np
data2 = np.random.rand(2,3)
data2

array([[0.02724334, 0.01078389, 0.36927907],
       [0.24599195, 0.04511977, 0.97543897]])

In [42]:
# 문제 3. 균일 분포에서 정수 난수 1개 생성하기
# 난수 객체 이름: data3
# 난수 범위: (1, 20)

# 정답 3.
import numpy as np
data3 = np.random.randint(1, 20)
data3

3

In [43]:
# 문제 4. data 배열에 10 곱하기

# 정답 4.
data*10
print(data * 10)



[[-0.23923686  1.2152216   2.96653406]
 [ 8.06717325 -9.18481446 12.08166388]]


In [44]:
# 문제 5. data 배열에 data 배열 더하기

# 정답 5.
data+data
print(data + data)

[[-0.04784737  0.24304432  0.59330681]
 [ 1.61343465 -1.83696289  2.41633278]]


In [45]:
# 문제 6. data 배열 크기 출력하기

# 정답 6.
print(data.shape)

(2, 3)


In [46]:
# 문제 7. data 데이터타입 출력하기

# 정답 7.
type(data)

numpy.ndarray

In [47]:
# 문제 8. 아래 리스트를 이용하여 NumPy ndarray 생성하기
# ndarray 이름: arr1

data1 = [6, 7.5, 8, 0, 1]

# 정답 8.
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [48]:
# 문제 9. 아래 리스트를 이용하여 ndarray 생성하기
# ndarray 이름: arr2
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

# 정답 9.
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
# 문제 10. 크기 10이고 0으로 초기화한 ndarray 생성하기
# ndarray 이름: data_zero

# 정답 10.
data_zero = np.zeros(10)
data_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
# 문제 11. 크기 (3, 6)이고 0으로 초기화한 ndarray 생성하기
# ndarray 이름: data_zero1

# 정답 11.
data_zero1 = np.zeros((3,6))
data_zero1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [51]:
# 문제 12. 크기 (2, 3, 2)이고 초기화하지 않은 ndarray 생성하기
# ndarray 이름: data_empty

# 정답 12.
data_empty = np.empty((2,3,2))
data_empty

array([[[ 2.00000000e+000,  2.00000000e+000],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 2.00000000e+000, -1.29073676e-231]],

       [[ 6.92830008e-310,  6.92830008e-310],
        [ 2.00000000e+000, -2.32034861e+077],
        [ 9.88131292e-324,  8.34402697e-309]]])

In [52]:
# 문제 13. 0 부터 15 전까지 시퀀스 배열 생성하기

# 정답 13.
sequence = np.arange(15)
sequence

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
# 문제 14. 0 부터 2 전까지 스텝크기 0.1 인 시퀀스 배열 생성하기

# 정답 14.
sequence1 = np.arange(0,2,0.1)
sequence1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [54]:
# 문제 15. 아래의 리스트를 이용하여 데이터타입이 np.float64인 ndarray 생성하기
# ndarray 이름: arr1
data_list = [1, 2, 3]

# 정답 15.
arr1 = np.float64(data_list)
arr1

array([1., 2., 3.])

In [60]:
# 문제 16. 아래의 리스트를 이용하여 데이터타입이 np.int32인 ndarray 생성하기
# ndarray 이름: arr2
data_list = [1, 2, 3, 4, 5]

# 정답 16.
arr2 = np.int32(data_list)
arr2

array([1, 2, 3, 4, 5], dtype=int32)

In [63]:
# 문제 17. 문제 16에서 생성한 arr2의 데이터타입을 np.float64 로 변환한 ndarray의 데이터타입 출력하기
# ndarray 이름: float_arr

# 정답 17.
float_arr = np.array(arr2, dtype=np.float64)
float_arr.dtype

dtype('float64')

In [65]:
# 문제 18. 아래의 ndarray를 np.int32 로 변환한 ndarray 생성하기
# ndarray 이름: int_arr
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

# 정답 18.
int_arr = np.array(arr, dtype=np.int32)
int_arr

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [67]:
# 문제 19. 아래의 ndarray를 np.float64로 변환한 ndarray 생성하기
# ndarray 이름: float_arr
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

# 정답 19.
float_arr = np.array(numeric_strings, dtype=np.float64)
float_arr

array([ 1.25, -9.6 , 42.  ])

In [68]:
# 문제 20. 아래 2개의 ndarray 간의 element-wise 곱하기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[4., 5., 6.], [1., 2., 3.]])

# 정답 20.
np.multiply(arr1, arr2)

array([[ 4., 10., 18.],
       [ 4., 10., 18.]])

In [70]:
# 문제 21. 아래 2개의 ndarray 간의 element-wise 나누기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[4., 5., 6.], [1., 2., 3.]])

# 정답 21.
np.divide(arr1,arr2)

array([[0.25, 0.4 , 0.5 ],
       [4.  , 2.5 , 2.  ]])

In [71]:
# 문제 22. 아래 ndarray에 element-wise 0.5 거듭제곱하기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])

# 정답 22.
arr**0.5

array([1.92353841,        nan,        nan, 0.70710678, 3.591657  ,
       3.17804972])

In [72]:
# 문제 23. 아래 ndarray을 transpose하기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])

# 정답 23.
np.transpose(arr1)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [74]:
# 문제 24. 아래 2개의 ndarray을 행렬 곱하여 arr3 생성하기
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = arr1.T

# 정답 24.
arr3 = np.dot(arr1, arr2)
arr3

array([[14., 32.],
       [32., 77.]])

In [75]:
# 문제 25. arr1이 3.5보다 큰지에 대해 불린 배열 출력하기
arr1 = np.array([1., 2., 3., 4., 5., 6.])

# 정답 25.
print(arr1 > 3.5)

[False False False  True  True  True]


In [77]:
# 문제 26. arr1이 3.5보다 큰 배열 인덱스 출력하기
arr1 = np.array([1., 2., 3., 4., 5., 6.])

# 정답 26.
arr1[arr1 > 3.5]

array([4., 5., 6.])

In [82]:
# 문제 27. arr2중에서 가장 큰 값 출력하기
arr2 = np.array([4., 5., 6., 1., 2., 3.])

# 정답 27.
np.max(arr2)

6.0

In [88]:
# 문제 28. arr2중에서 가장 큰 값 인덱스 출력하기
arr2 = np.array([4., 5., 6., 1., 2., 3.])

# 정답 28.
np.argmax(arr2)

2

In [89]:
# 문제 29. arr2 오름차순으로 정렬하기
arr2 = np.array([4., 5., 6., 1., 2., 3.])

# 정답 29.
np.sort(arr2)

array([1., 2., 3., 4., 5., 6.])

In [90]:
# 문제 30. arr2 오름차순으로 정렬했을 때의 인덱스 출력하기
arr2 = np.array([4., 5., 6., 1., 2., 3.])

# 정답 30.
np.argsort(arr2)

array([3, 4, 5, 0, 1, 2])

In [106]:
# 문제 31. 아래 arr 배열 인덱스 5부터 8전까지의 값을 12로 변경하기 
arr = np.arange(10)

# 정답 31.
arr
[12 if 5 <= i < 8 else i for i in arr]

[0, 1, 2, 3, 4, 12, 12, 12, 8, 9]

In [112]:
# 문제 32. 문제 29의 arr 배열의 인덱스 5부터 8전까지를 슬라이싱하여 arr_slice 배열 생성하기

# 정답 32.
arr = np.arange(10)

arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [120]:
# 문제 33. 문제 30의 arr_slice의 인덱스 1번째 값을 12345로 변경하고 arr 배열 출력하기
# arr 배열의 값이 왜 변경되었을까 생각해보기

# 정답 33.
arr_slice
arr_slice[1] = 12345
arr
# arr 배열의 값이 변경 된 이유 : arr 배열에서 슬라이싱을 하여 arr_slice 배열을 생성해도 원본 arr배열을 copy해서 사용하는것이 아니라 arr배열 원본 그 자체를 공유하고 있기 때문입니다.(array를 관리 할 때 메모리 문제를 피하기 위해 numpy에서 관리하는 방법)

# 그럼 원본 arr배열이 안바뀌도록 하려면 arr.copy()함수를 사용하여 복사를 하면 됩니다.

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

-5
c    3
a   -5
d    6
dtype: int64


In [125]:
# 문제 34. 문제 31의 arr_slice 배열의 모든 값을 64로 변경하고 arr 배열 출력하기

# 정답 34.
arr_slice
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [127]:
# 문제 35. 문제 31의 arr_slice 배열의 복사본을 생성하고 모든 값을 9999로 변경하고 arr 배열 출력하기

# 정답 35.
arr_slice_copy = arr_slice.copy()
arr_slice_copy[:] = 9999
arr
# 복사본을 만들었으므로 원본 arr 배열에는 영향을 주지 않습니다.

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])